language: bash
services: docker

env:
  - DIR=master
  - DIR=master VARIANT=alpine
  - DIR=20
  - DIR=20 VARIANT=slim
  - DIR=20 VARIANT=alpine
  - DIR=19
  - DIR=19 VARIANT=slim

before_script:
  - cd "$DIR"
  - eval $(awk '/OTP_VERSION=/ { sub(/@/, "-", $2); print $2; exit }' ${VARIANT:-.}/Dockerfile)
  - image="erlang:${OTP_VERSION}${VARIANT:+-$VARIANT}"

script:
  - docker build --pull -t "$image" "${VARIANT:-.}"
  - curl -fsSL https://github.com/docker-library/official-images/archive/master.tar.gz | tar -zxvv official-images-master/test/
  - ./official-images-master/test/run.sh "$image"

after_script:
  - docker images
